const router = require('express').Router()
const location = require('./locationRoutes')
const buyer = require('./buyerRoutes')
const seller = require('./sellerRoutes')
const category = require('./categotyRoutes')
const elastic = require('./elasticSearchRoutes')
const user = require('./userRoutes')
const subscriptionPlan = require('./subscriptionPlanRoutes')
const contact = require('./contactRoutes')
const removeListing = require('./removeListingRoutes')
const payment = require('./paymentRoutes')

router.use(location)
router.use(buyer)
router.use(seller)
router.use(category)
router.use(elastic)
router.use(user)
router.use(subscriptionPlan)
router.use(contact)
router.use(removeListing)
router.use(payment)

module.exports = router