###
POST http://localhost:8070/api/addParentCategories HTTP/1.1
content-type: application/json

[
  {
    "vendorId": 14,
    "name": "Automobiles"
  },
  {
    "vendorId": 23,
    "name": "Cosmetics"
  }
]
