###
POST http://localhost:8070/api/addPrimaryCategories HTTP/1.1
content-type: application/json

[
  {
    "vendorId": "HMT1",
    "parentId": 18,
    "name": "Pliers, Screwdrivers & Hammers"
  },
  {
    "vendorId": "HMT2",
    "parentId": 18,
    "name": "Machine & Precision Tools"
  },
  {
    "vendorId": "HMT3",
    "parentId": 18,
    "name": "Cutting Tools & Milling Cutter"
  },
  {
    "vendorId": "HMT4",
    "parentId": 18,
    "name": "Gardening and Horticulture Tools"
  },
  {
    "vendorId": "HMT5",
    "parentId": 18,
    "name": "Hydraulic & Pneumatic Tools"
  },
  {
    "vendorId": "HMT6",
    "parentId": 18,
    "name": "Cutting Blades, Knives and Scissors"
  },
  {
    "vendorId": "HMT7",
    "parentId": 18,
    "name": "Jewellery Making Tools & Machines"
  },
  {
    "vendorId": "HMT8",
    "parentId": 18,
    "name": "Woodworking Tools & Machines"
  },
  {
    "vendorId": "HMT9",
    "parentId": 18,
    "name": "Buffing, Surface Finishing Machines"
  },
  {
    "vendorId": "HMT10",
    "parentId": 18,
    "name": "Shearing, Trimming & Metal Profiling"
  },
  {
    "vendorId": "HMT11",
    "parentId": 18,
    "name": "Saws, Chainsaws and Saw Blades"
  },
  {
    "vendorId": "HMT12",
    "parentId": 18,
    "name": "Electrical & Electronic Goods Repair"
  },
  {
    "vendorId": "HMT13",
    "parentId": 18,
    "name": "Marine Tools & Equipments"
  },
  {
    "vendorId": "MM1",
    "parentId": 17,
    "name": "Metal & Metal Made Products"
  },
  {
    "vendorId": "MM2",
    "parentId": 17,
    "name": "Minerals and Ores"
  },
  {
    "vendorId": "MM3",
    "parentId": 17,
    "name": "Iron & Copper Alloys"
  },
  {
    "vendorId": "MM4",
    "parentId": 17,
    "name": "Coal, Carbon & Charcoal"
  },
  {
    "vendorId": "MM5",
    "parentId": 17,
    "name": "Copper & Brass Products"
  },
  {
    "vendorId": "MM6",
    "parentId": 17,
    "name": "Ironware, Ironmongery & Iron Artware"
  },
  {
    "vendorId": "MM7",
    "parentId": 17,
    "name": "Mica & Mica Products"
  },
  {
    "vendorId": "MM8",
    "parentId": 17,
    "name": "Aluminium and Aluminium Products"
  },
  {
    "vendorId": "PMG1",
    "parentId": 9,
    "name": "Barcode, Stickers & Luggage Tags"
  },
  {
    "vendorId": "PMG2",
    "parentId": 9,
    "name": "Food Packaging Materials & Supplies"
  },
  {
    "vendorId": "PMG3",
    "parentId": 9,
    "name": "Labels: Adhesive, Fabric & Metal"
  },
  {
    "vendorId": "PMG4",
    "parentId": 9,
    "name": "Packaging Films & Foils"
  },
  {
    "vendorId": "PMG5",
    "parentId": 9,
    "name": "Crates, Trays and Pallets"
  },
  {
    "vendorId": "PMG6",
    "parentId": 9,
    "name": "Packaging Caps & Seals"
  },
  {
    "vendorId": "PMG7",
    "parentId": 9,
    "name": "Filling Machines & Plants"
  },
  {
    "vendorId": "PMG8",
    "parentId": 9,
    "name": "Packaging, Laminated & Zip Bags"
  },
  {
    "vendorId": "PMG9",
    "parentId": 9,
    "name": "Plastic Containers & Bottles"
  },
  {
    "vendorId": "PMG10",
    "parentId": 9,
    "name": "Protective Packing Materials"
  },
  {
    "vendorId": "PMG11",
    "parentId": 9,
    "name": "Packaging Pouches & Envelopes"
  },
  {
    "vendorId": "PMG12",
    "parentId": 9,
    "name": "Form Fill & Seal Machines"
  },
  {
    "vendorId": "PMG13",
    "parentId": 9,
    "name": "Marking and Stamping Machines"
  },
  {
    "vendorId": "PMG14",
    "parentId": 9,
    "name": "Bulk Bags & Sacks"
  },
  {
    "vendorId": "PMG15",
    "parentId": 9,
    "name": "Aluminium,Tin Can & Metal Containers"
  },
  {
    "vendorId": "PMG16",
    "parentId": 9,
    "name": "Corrugated Packaging Boxes"
  },
  {
    "vendorId": "PMG17",
    "parentId": 9,
    "name": "Wrapping & Banding Machines"
  },
  {
    "vendorId": "PMG18",
    "parentId": 9,
    "name": "Packing Straps, Clips & Supplies"
  },
  {
    "vendorId": "PMG19",
    "parentId": 9,
    "name": "Product Packing & Labelling Services"
  }
]