###
POST http://localhost:8070/api/addPrimaryCategories HTTP/1.1
content-type: application/json

[
  {
    "vendorId": "SGT1",
    "parentId": 31,
    "name": "Sports Wear & Athletic Accessories"
  },
  {
    "vendorId": "SGT2",
    "parentId": 31,
    "name": "Team Sports Goods & Supplies"
  },
  {
    "vendorId": "SGT3",
    "parentId": 31,
    "name": "Swimming Pool & Water Sport Goods"
  },
  {
    "vendorId": "SGT4",
    "parentId": 31,
    "name": "Inflatable Toys and Preschool Toys"
  },
  {
    "vendorId": "SGT5",
    "parentId": 31,
    "name": "Figure Toys and Vehicle Toys"
  },
  {
    "vendorId": "SGT6",
    "parentId": 31,
    "name": "Dumbbell, Weight Plate & Accessories"
  },
  {
    "vendorId": "SGT7",
    "parentId": 31,
    "name": "Exercise Bikes & Fitness Equipments"
  },
  {
    "vendorId": "SGT8",
    "parentId": 31,
    "name": "Fun Parks & Amusement Park Equipment"
  },
  {
    "vendorId": "SGT9",
    "parentId": 31,
    "name": "Puzzles, Board & Educational Games"
  },
  {
    "vendorId": "SGT10",
    "parentId": 31,
    "name": "Playstations & Video Arcade Games"
  },
  {
    "vendorId": "SGT11",
    "parentId": 31,
    "name": "Camping, Fishing & Hunting Goods"
  },
  {
    "vendorId": "SGT12",
    "parentId": 31,
    "name": "Table Sports & Board Games"
  },
  {
    "vendorId": "SGT13",
    "parentId": 31,
    "name": "Sports Shoes, Footwear & Accessories"
  },
  {
    "vendorId": "SGT14",
    "parentId": 31,
    "name": "Exercise & Fitness Equipment"
  },
  {
    "vendorId": "SGT15",
    "parentId": 31,
    "name": "Stuffed Toys, Puppets & Dolls"
  },
  {
    "vendorId": "SGT16",
    "parentId": 31,
    "name": "Sports Training Aids & Equipments"
  },
  {
    "vendorId": "SGT17",
    "parentId": 31,
    "name": "Adventure Sporting & Trekking Goods"
  },
  {
    "vendorId": "SGT18",
    "parentId": 31,
    "name": "Racquet Sporting Goods & Supplies"
  },
  {
    "vendorId": "SGT19",
    "parentId": 31,
    "name": "Target Sports Goods & Supplies"
  },
  {
    "vendorId": "SGT20",
    "parentId": 31,
    "name": "Track & Field Equipment"
  },
  {
    "vendorId": "SGT21",
    "parentId": 31,
    "name": "Boxing and Martial Arts Goods"
  },
  {
    "vendorId": "SGT22",
    "parentId": 31,
    "name": "Snow Sports Goods & Gears"
  },
  {
    "vendorId": "SGT23",
    "parentId": 31,
    "name": "Gymnastics & Aerobics"
  },
  {
    "vendorId": "SGT24",
    "parentId": 31,
    "name": "Sports Bags, Duffel Bags & Kit Bags"
  }
]