###
POST http://localhost:8070/api/addSecondaryCategories HTTP/1.1
content-type: application/json

# POST http://localhost:8070/api/l3_delete HTTP/1.1
# content-type: application/json

[
  {
    "vendorId": "L3SGT1",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports T Shirts"
  },
  {
    "vendorId": "L3SGT2",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Tracksuits"
  },
  {
    "vendorId": "L3SGT3",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Pant"
  },
  {
    "vendorId": "L3SGT4",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Wear"
  },
  {
    "vendorId": "L3SGT5",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Shorts"
  },
  {
    "vendorId": "L3SGT6",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Jersey"
  },
  {
    "vendorId": "L3SGT7",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Jackets"
  },
  {
    "vendorId": "L3SGT8",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Polo Shirts"
  },
  {
    "vendorId": "L3SGT9",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Socks"
  },
  {
    "vendorId": "L3SGT10",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sporting Gloves"
  },
  {
    "vendorId": "L3SGT11",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Swimwear"
  },
  {
    "vendorId": "L3SGT12",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Sports Suit"
  },
  {
    "vendorId": "L3SGT13",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Football Clothes & Shoes"
  },
  {
    "vendorId": "L3SGT14",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Hockey Apparel"
  },
  {
    "vendorId": "L3SGT15",
    "primaryCatId": "SGT1",
    "level1 id": 31,
    "name": "Baseball Uniforms"
  },
  {
    "vendorId": "L3SGT16",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Cricket Bat"
  },
  {
    "vendorId": "L3SGT17",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Football"
  },
  {
    "vendorId": "L3SGT18",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Cricket Ball"
  },
  {
    "vendorId": "L3SGT19",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Sports Balls"
  },
  {
    "vendorId": "L3SGT20",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Cricket Equipment"
  },
  {
    "vendorId": "L3SGT21",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Cricket Kits"
  },
  {
    "vendorId": "L3SGT22",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Hockey Equipment"
  },
  {
    "vendorId": "L3SGT23",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Basketball Equipment"
  },
  {
    "vendorId": "L3SGT24",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Volleyball Equipment"
  },
  {
    "vendorId": "L3SGT25",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Football Balls & Goals"
  },
  {
    "vendorId": "L3SGT26",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Basketball Accessories"
  },
  {
    "vendorId": "L3SGT27",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Soccer Kit"
  },
  {
    "vendorId": "L3SGT28",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Baseball Equipment"
  },
  {
    "vendorId": "L3SGT29",
    "primaryCatId": "SGT2",
    "level1 id": 31,
    "name": "Soccer Equipment"
  },
  {
    "vendorId": "L3SGT30",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pools"
  },
  {
    "vendorId": "L3SGT31",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Filters"
  },
  {
    "vendorId": "L3SGT32",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Chemicals"
  },
  {
    "vendorId": "L3SGT33",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Accessories"
  },
  {
    "vendorId": "L3SGT34",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Equipment"
  },
  {
    "vendorId": "L3SGT35",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Goggles"
  },
  {
    "vendorId": "L3SGT36",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Boats"
  },
  {
    "vendorId": "L3SGT37",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Pumps"
  },
  {
    "vendorId": "L3SGT38",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Cleaners"
  },
  {
    "vendorId": "L3SGT39",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Furniture"
  },
  {
    "vendorId": "L3SGT40",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Inflatable Boats"
  },
  {
    "vendorId": "L3SGT41",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Diving Accessories"
  },
  {
    "vendorId": "L3SGT42",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Accessories"
  },
  {
    "vendorId": "L3SGT43",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Swimming Pool Toys"
  },
  {
    "vendorId": "L3SGT44",
    "primaryCatId": "SGT3",
    "level1 id": 31,
    "name": "Bleaching Powder"
  },
  {
    "vendorId": "L3SGT45",
    "primaryCatId": "SGT4",
    "level1 id": 31,
    "name": "Kids Toys"
  },
  {
    "vendorId": "L3SGT46",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Dumbbells"
  },
  {
    "vendorId": "L3SGT47",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Weight Plate"
  },
  {
    "vendorId": "L3SGT48",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Home Gym Equipment"
  },
  {
    "vendorId": "L3SGT49",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Exercise Ball"
  },
  {
    "vendorId": "L3SGT50",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Sports Mats"
  },
  {
    "vendorId": "L3SGT51",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Yoga Accessories"
  },
  {
    "vendorId": "L3SGT52",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Gym Bar"
  },
  {
    "vendorId": "L3SGT53",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Gym Rope"
  },
  {
    "vendorId": "L3SGT54",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Free Weights"
  },
  {
    "vendorId": "L3SGT55",
    "primaryCatId": "SGT6",
    "level1 id": 31,
    "name": "Exercise Benches"
  },
  {
    "vendorId": "L3SGT56",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Exercise Bike"
  },
  {
    "vendorId": "L3SGT57",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Exercise Treadmill"
  },
  {
    "vendorId": "L3SGT58",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Abdominal Machine"
  },
  {
    "vendorId": "L3SGT59",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Ellipticals"
  },
  {
    "vendorId": "L3SGT60",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Multifunction Fitness Equipment"
  },
  {
    "vendorId": "L3SGT61",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Leg Exercise Equipment"
  },
  {
    "vendorId": "L3SGT62",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Slimming Machines"
  },
  {
    "vendorId": "L3SGT63",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Cardio Machines"
  },
  {
    "vendorId": "L3SGT64",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Exercise Stepper"
  },
  {
    "vendorId": "L3SGT65",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Chest Exercise Machine"
  },
  {
    "vendorId": "L3SGT66",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Back Exercise Machine"
  },
  {
    "vendorId": "L3SGT67",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Arm Exercise Machines"
  },
  {
    "vendorId": "L3SGT68",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Treadmill Parts"
  },
  {
    "vendorId": "L3SGT69",
    "primaryCatId": "SGT7",
    "level1 id": 31,
    "name": "Full Body Exercise Machines"
  },
  {
    "vendorId": "L3SGT70",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Playground Slide"
  },
  {
    "vendorId": "L3SGT71",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Children Swing"
  },
  {
    "vendorId": "L3SGT72",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Amusement Rides"
  },
  {
    "vendorId": "L3SGT73",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Kids Play Equipment"
  },
  {
    "vendorId": "L3SGT74",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Amusement Park Equipments"
  },
  {
    "vendorId": "L3SGT75",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Playground Climber"
  },
  {
    "vendorId": "L3SGT76",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Water Slides"
  },
  {
    "vendorId": "L3SGT77",
    "primaryCatId": "SGT8",
    "level1 id": 31,
    "name": "Amusement Park Inflatable"
  },
  {
    "vendorId": "L3SGT78",
    "primaryCatId": "SGT9",
    "level1 id": 31,
    "name": "Mind Games"
  },
  {
    "vendorId": "L3SGT79",
    "primaryCatId": "SGT10",
    "level1 id": 31,
    "name": "Video Games"
  },
  {
    "vendorId": "L3SGT80",
    "primaryCatId": "SGT11",
    "level1 id": 31,
    "name": "Camping Tents"
  },
  {
    "vendorId": "L3SGT81",
    "primaryCatId": "SGT13",
    "level1 id": 31,
    "name": "Sports Shoes"
  },
  {
    "vendorId": "L3SGT82",
    "primaryCatId": "SGT13",
    "level1 id": 31,
    "name": "Running Shoes"
  },
  {
    "vendorId": "L3SGT83",
    "primaryCatId": "SGT13",
    "level1 id": 31,
    "name": "Outdoor Sports Shoes"
  },
  {
    "vendorId": "L3SGT84",
    "primaryCatId": "SGT13",
    "level1 id": 31,
    "name": "Indoor Shoes"
  },
  {
    "vendorId": "L3SGT85",
    "primaryCatId": "SGT14",
    "level1 id": 31,
    "name": "Yoga Mat"
  },
  {
    "vendorId": "L3SGT86",
    "primaryCatId": "SGT14",
    "level1 id": 31,
    "name": "Skipping Ropes"
  },
  {
    "vendorId": "L3SGT87",
    "primaryCatId": "SGT14",
    "level1 id": 31,
    "name": "Exercise Benches"
  },
  {
    "vendorId": "L3SGT88",
    "primaryCatId": "SGT14",
    "level1 id": 31,
    "name": "Exercise Bands"
  },
  {
    "vendorId": "L3SGT89",
    "primaryCatId": "SGT15",
    "level1 id": 31,
    "name": "Soft Toy"
  },
  {
    "vendorId": "L3SGT90",
    "primaryCatId": "SGT16",
    "level1 id": 31,
    "name": "Sport Goods"
  },
  {
    "vendorId": "L3SGT91",
    "primaryCatId": "SGT15",
    "level1 id": 31,
    "name": "Chennapatna/Ramanagra Toys"
  },
  {
    "vendorId": "L3AF102",
    "primaryCatId": "AF2",
    "level1 id": 15,
    "name": "Plantation & Estate"
  }
]