###
POST http://localhost:8070/api/addBulkProducts HTTP/1.1
content-type: application/json

# POST http://localhost:8070/api/l4_delete HTTP/1.1
# content-type: application/json

[
  {
    "vendorId": "L4F1",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Basmati Rice"
  },
  {
    "vendorId": "L4F2",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Non Basmati Rice"
  },
  {
    "vendorId": "L4F3",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Broken Rice"
  },
  {
    "vendorId": "L4F4",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Brown Rice"
  },
  {
    "vendorId": "L4F5",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Long Grain Rice"
  },
  {
    "vendorId": "L4F6",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Parboiled Rice"
  },
  {
    "vendorId": "L4F7",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Organic Rice"
  },
  {
    "vendorId": "L4F8",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Paddy Rice"
  },
  {
    "vendorId": "L4F9",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Black Rice"
  },
  {
    "vendorId": "L4F10",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Golden Sella Rice"
  },
  {
    "vendorId": "L4F11",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Red Rice"
  },
  {
    "vendorId": "L4F12",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Short Grain Rice"
  },
  {
    "vendorId": "L4F13",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Medium Grain Rice"
  },
  {
    "vendorId": "L4F14",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Aromatic Rice"
  },
  {
    "vendorId": "L4F15",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Polished Rice"
  },
  {
    "vendorId": "L4F16",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Matta Rice"
  },
  {
    "vendorId": "L4F17",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Unpolished Rice"
  },
  {
    "vendorId": "L4F18",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Wild Rice"
  },
  {
    "vendorId": "L4F19",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Poongar Rice"
  },
  {
    "vendorId": "L4F20",
    "secondaryId": "L3F1",
    "l1": 3,
    "name": "Dubraj Rice"
  },
  {
    "vendorId": "L4F21",
    "secondaryId": "L3F2",
    "l1": 3,
    "name": "Wheat Grains"
  },
  {
    "vendorId": "L4F22",
    "secondaryId": "L3F3",
    "l1": 3,
    "name": "Pulses"
  },
  {
    "vendorId": "L4F23",
    "secondaryId": "L3F3",
    "l1": 3,
    "name": "Food Grains"
  },
  {
    "vendorId": "L4F24",
    "secondaryId": "L3F4",
    "l1": 3,
    "name": "Sugar"
  },
  {
    "vendorId": "L4F25",
    "secondaryId": "L3F4",
    "l1": 3,
    "name": "Jaggery"
  },
  {
    "vendorId": "L4F26",
    "secondaryId": "L3F5",
    "l1": 3,
    "name": "Wheat Flour"
  },
  {
    "vendorId": "L4F27",
    "secondaryId": "L3F5",
    "l1": 3,
    "name": "Other Flours"
  },
  {
    "vendorId": "L4F28",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Masala Powder"
  },
  {
    "vendorId": "L4F29",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Whole Spices"
  },
  {
    "vendorId": "L4F30",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Edible Salt"
  },
  {
    "vendorId": "L4F31",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Vegetable Powders"
  },
  {
    "vendorId": "L4F32",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Cooking Paste"
  },
  {
    "vendorId": "L4F33",
    "secondaryId": "L3F6",
    "l1": 3,
    "name": "Masala Mixes"
  },
  {
    "vendorId": "L4F34",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Mustard Oil"
  },
  {
    "vendorId": "L4F35",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Palm Oil"
  },
  {
    "vendorId": "L4F36",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Sunflower Oil"
  },
  {
    "vendorId": "L4F37",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Groundnut Oil"
  },
  {
    "vendorId": "L4F38",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Coconut Oil"
  },
  {
    "vendorId": "L4F39",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Olive Oil"
  },
  {
    "vendorId": "L4F40",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Castor Oil"
  },
  {
    "vendorId": "L4F41",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Fish Oil"
  },
  {
    "vendorId": "L4F42",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Carrier Oil"
  },
  {
    "vendorId": "L4F43",
    "secondaryId": "L3F7",
    "l1": 3,
    "name": "Nut Oils"
  },
  {
    "vendorId": "L4F44",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Milk"
  },
  {
    "vendorId": "L4F45",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Ghee"
  },
  {
    "vendorId": "L4F46",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Butter"
  },
  {
    "vendorId": "L4F47",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Paneer"
  },
  {
    "vendorId": "L4F48",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Curd"
  },
  {
    "vendorId": "L4F49",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Ice Cream"
  },
  {
    "vendorId": "L4F50",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Milk Proteins"
  },
  {
    "vendorId": "L4F51",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Cheese"
  },
  {
    "vendorId": "L4F52",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Milk Powder"
  },
  {
    "vendorId": "L4F53",
    "secondaryId": "L3F8",
    "l1": 3,
    "name": "Flavoured Milk"
  },
  {
    "vendorId": "L4F54",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Fresh Vegetables"
  },
  {
    "vendorId": "L4F55",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Onion"
  },
  {
    "vendorId": "L4F56",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Mushroom"
  },
  {
    "vendorId": "L4F57",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Chilli"
  },
  {
    "vendorId": "L4F58",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Dried Vegetables"
  },
  {
    "vendorId": "L4F59",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Frozen Vegetables"
  },
  {
    "vendorId": "L4F60",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Beans"
  },
  {
    "vendorId": "L4F61",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Vegetable Granule"
  },
  {
    "vendorId": "L4F62",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Exotic Vegetables"
  },
  {
    "vendorId": "L4F63",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Vegetable & Herb Flakes"
  },
  {
    "vendorId": "L4F64",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Fruit Pulp"
  },
  {
    "vendorId": "L4F65",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Mangoes"
  },
  {
    "vendorId": "L4F66",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Coconut"
  },
  {
    "vendorId": "L4F67",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Apple"
  },
  {
    "vendorId": "L4F68",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Frozen Fruits"
  },
  {
    "vendorId": "L4F69",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Preserved Fruits"
  },
  {
    "vendorId": "L4F70",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Citrus Fruits"
  },
  {
    "vendorId": "L4F71",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Berries"
  },
  {
    "vendorId": "L4F72",
    "secondaryId": "L3F9",
    "l1": 3,
    "name": "Other Fresh Fruits"
  },
  {
    "vendorId": "L4F73",
    "secondaryId": "L3F10",
    "l1": 3,
    "name": "Egg"
  },
  {
    "vendorId": "L4F74",
    "secondaryId": "L3F10",
    "l1": 3,
    "name": "Poultry & Other Meat Products"
  },
  {
    "vendorId": "L4F75",
    "secondaryId": "L3F11",
    "l1": 3,
    "name": "Fresh Fish"
  },
  {
    "vendorId": "L4F76",
    "secondaryId": "L3F11",
    "l1": 3,
    "name": "Seafood"
  },
  {
    "vendorId": "L4F77",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Colors"
  },
  {
    "vendorId": "L4F78",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Flavour"
  },
  {
    "vendorId": "L4F79",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Vinegar"
  },
  {
    "vendorId": "L4F80",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Antioxidants"
  },
  {
    "vendorId": "L4F81",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Grade Chemical"
  },
  {
    "vendorId": "L4F82",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Starch Powder"
  },
  {
    "vendorId": "L4F83",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Sweetener"
  },
  {
    "vendorId": "L4F84",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Bakery & Confectionery Flavors"
  },
  {
    "vendorId": "L4F85",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Enzymes"
  },
  {
    "vendorId": "L4F86",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Preservative"
  },
  {
    "vendorId": "L4F87",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Invert Sugar Syrup"
  },
  {
    "vendorId": "L4F88",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Beverage Flavors"
  },
  {
    "vendorId": "L4F89",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Emulsifiers"
  },
  {
    "vendorId": "L4F90",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Acidulant"
  },
  {
    "vendorId": "L4F91",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Dough Conditioners"
  },
  {
    "vendorId": "L4F92",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Anti Caking Agents"
  },
  {
    "vendorId": "L4F93",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Food Stabilizer"
  },
  {
    "vendorId": "L4F94",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Aroma Flavour"
  },
  {
    "vendorId": "L4F95",
    "secondaryId": "L3F12",
    "l1": 3,
    "name": "Dessert Flavor"
  },
  {
    "vendorId": "L4F96",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Papad"
  },
  {
    "vendorId": "L4F97",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Chips"
  },
  {
    "vendorId": "L4F98",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Sev and Bhujia"
  },
  {
    "vendorId": "L4F99",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Khakhra"
  },
  {
    "vendorId": "L4F100",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Fryums"
  },
  {
    "vendorId": "L4F101",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Healthy Food Snacks & Popcorn"
  },
  {
    "vendorId": "L4F102",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Veg Snacks"
  },
  {
    "vendorId": "L4F103",
    "secondaryId": "L3F13",
    "l1": 3,
    "name": "Non Veg Snack"
  },
  {
    "vendorId": "L4F104",
    "secondaryId": "L3F14",
    "l1": 3,
    "name": "Pickles"
  },
  {
    "vendorId": "L4F105",
    "secondaryId": "L3F14",
    "l1": 3,
    "name": "Chutneys"
  },
  {
    "vendorId": "L4F106",
    "secondaryId": "L3F15",
    "l1": 3,
    "name": "Jams"
  },
  {
    "vendorId": "L4F107",
    "secondaryId": "L3F15",
    "l1": 3,
    "name": "Ketchups & Sauces"
  },
  {
    "vendorId": "L4F108",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Ready to Eat Food"
  },
  {
    "vendorId": "L4F109",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Pasta & Soups"
  },
  {
    "vendorId": "L4F110",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Frozen Food"
  },
  {
    "vendorId": "L4F111",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Instant Mixes"
  },
  {
    "vendorId": "L4F112",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Breakfast Cereals"
  },
  {
    "vendorId": "L4F113",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Canned Food"
  },
  {
    "vendorId": "L4F114",
    "secondaryId": "L3F16",
    "l1": 3,
    "name": "Noodles & Vermicelli"
  },
  {
    "vendorId": "L4F115",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Milk Sweets"
  },
  {
    "vendorId": "L4F116",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Laddu"
  },
  {
    "vendorId": "L4F117",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Barfi"
  },
  {
    "vendorId": "L4F118",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Soan Papdi"
  },
  {
    "vendorId": "L4F119",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Chikki"
  },
  {
    "vendorId": "L4F120",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Peda"
  },
  {
    "vendorId": "L4F121",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Gazak"
  },
  {
    "vendorId": "L4F122",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Halwa"
  },
  {
    "vendorId": "L4F123",
    "secondaryId": "L3F17",
    "l1": 3,
    "name": "Other Sweets"
  },
  {
    "vendorId": "L4F124",
    "secondaryId": "L3F18",
    "l1": 3,
    "name": "Cashew Nuts (Kaju)"
  },
  {
    "vendorId": "L4F125",
    "secondaryId": "L3F18",
    "l1": 3,
    "name": "Almond"
  },
  {
    "vendorId": "L4F126",
    "secondaryId": "L3F18",
    "l1": 3,
    "name": "Walnut"
  },
  {
    "vendorId": "L4F127",
    "secondaryId": "L3F19",
    "l1": 3,
    "name": "Other Dry Fruits & Nuts"
  },
  {
    "vendorId": "L4F128",
    "secondaryId": "L3F19",
    "l1": 3,
    "name": "Dry Dates"
  },
  {
    "vendorId": "L4F129",
    "secondaryId": "L3F19",
    "l1": 3,
    "name": "Raisins"
  },
  {
    "vendorId": "L4F130",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Fruit Juice"
  },
  {
    "vendorId": "L4F131",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Fruit Syrups"
  },
  {
    "vendorId": "L4F132",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Fruit Squashes"
  },
  {
    "vendorId": "L4F133",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Instant Drink Mix"
  },
  {
    "vendorId": "L4F134",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Vegetable Juices"
  },
  {
    "vendorId": "L4F135",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Drinking Water"
  },
  {
    "vendorId": "L4F136",
    "secondaryId": "L3F20",
    "l1": 3,
    "name": "Carbonated Drinks"
  },
  {
    "vendorId": "L4F137",
    "secondaryId": "L3F21",
    "l1": 3,
    "name": "Tea"
  },
  {
    "vendorId": "L4F138",
    "secondaryId": "L3F21",
    "l1": 3,
    "name": "Green Tea"
  },
  {
    "vendorId": "L4F139",
    "secondaryId": "L3F21",
    "l1": 3,
    "name": "Coffee Beans"
  },
  {
    "vendorId": "L4F140",
    "secondaryId": "L3F21",
    "l1": 3,
    "name": "Coffee Powder"
  },
  {
    "vendorId": "L4F141",
    "secondaryId": "L3F21",
    "l1": 3,
    "name": "Coffee Substitutes"
  },
  {
    "vendorId": "L4F142",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Cake"
  },
  {
    "vendorId": "L4F143",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Bread & Buns"
  },
  {
    "vendorId": "L4F144",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Rusk Toast"
  },
  {
    "vendorId": "L4F145",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Pastry"
  },
  {
    "vendorId": "L4F146",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Muffin & Cupcakes"
  },
  {
    "vendorId": "L4F147",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Ice Cream Raw Materials"
  },
  {
    "vendorId": "L4F148",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Pies"
  },
  {
    "vendorId": "L4F149",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Bakery Sweets"
  },
  {
    "vendorId": "L4F150",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Confectionery Ingredients"
  },
  {
    "vendorId": "L4F151",
    "secondaryId": "L3F22",
    "l1": 3,
    "name": "Biscuits & Cookies"
  },
  {
    "vendorId": "L4F152",
    "secondaryId": "L3F23",
    "l1": 3,
    "name": "Chocolate Snacks & Chocolates"
  },
  {
    "vendorId": "L4F153",
    "secondaryId": "L3F23",
    "l1": 3,
    "name": "Jellies & Candies"
  }
]